using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StyleLearner.Detectors;

public class UsingDirectiveDetector : IStyleDetector
{
    public string Name => "Using Directives";

    private int _sortedCount;
    private int _unsortedCount;
    private int _systemFirstCount;
    private int _systemMixedCount;
    private int _groupedCount;
    private int _ungroupedCount;
    private int _outsideCount;
    private int _insideCount;

    private readonly ExampleCollector _examples = new();

    public void Analyze(SyntaxTree tree, string filePath)
    {
        _examples.SetContext(tree, filePath);

        // Skip auto-generated files
        var sourceText = tree.GetText();
        if (sourceText.Lines.Count > 0)
        {
            var firstLine = sourceText.Lines[0].ToString();
            if (firstLine.Contains("// <auto-generated"))
                return;
        }

        var root = (CompilationUnitSyntax)tree.GetRoot();

        // Top-level usings (outside namespace)
        var topLevelUsings = root.Usings
            .Where(u => !u.GlobalKeyword.IsKind(SyntaxKind.GlobalKeyword))
            .ToList();

        if (topLevelUsings.Count >= 2)
        {
            _outsideCount++;
            AnalyzeUsingBlock(topLevelUsings, tree);
        }

        // Block-scoped namespace usings (inside namespace)
        foreach (var ns in root.Members.OfType<NamespaceDeclarationSyntax>())
        {
            var nsUsings = ns.Usings
                .Where(u => !u.GlobalKeyword.IsKind(SyntaxKind.GlobalKeyword))
                .ToList();

            if (nsUsings.Count >= 2)
            {
                _insideCount++;
                AnalyzeUsingBlock(nsUsings, tree);
            }
        }
    }

    private void AnalyzeUsingBlock(List<UsingDirectiveSyntax> usings, SyntaxTree tree)
    {
        // Separate regular usings from static and alias
        var regularUsings = usings
            .Where(u => !u.StaticKeyword.IsKind(SyntaxKind.StaticKeyword) && u.Alias == null)
            .ToList();

        if (regularUsings.Count < 2)
            return;

        var names = regularUsings.Select(u => u.Name?.ToString() ?? "").ToList();

        // D1: Check alphabetical sort (case-insensitive)
        bool isSorted = IsSortedAlpha(names);
        if (isSorted)
            _sortedCount++;
        else
        {
            _unsortedCount++;
            int firstLine = regularUsings.First().GetLocation().GetLineSpan().StartLinePosition.Line;
            int lastLine = regularUsings.Last().GetLocation().GetLineSpan().EndLinePosition.Line;
            _examples.TryAdd("unsorted", firstLine, lastLine);
        }

        // D2: System-first check (only for files that have both System.* and non-System usings)
        bool hasSystem = names.Any(n => n.StartsWith("System"));
        bool hasNonSystem = names.Any(n => !n.StartsWith("System"));

        if (hasSystem && hasNonSystem)
        {
            int lastSystemIndex = -1;
            int firstNonSystemIndex = names.Count;

            for (int i = 0; i < names.Count; i++)
            {
                if (names[i].StartsWith("System"))
                    lastSystemIndex = i;
                else if (firstNonSystemIndex == names.Count)
                    firstNonSystemIndex = i;
            }

            if (lastSystemIndex < firstNonSystemIndex)
                _systemFirstCount++;
            else
                _systemMixedCount++;
        }

        // D3: Blank line grouping — check if there are blank lines between consecutive using directives
        var text = tree.GetText();
        bool hasGroupSeparator = false;

        for (int i = 0; i < usings.Count - 1; i++)
        {
            int endLine = usings[i].GetLocation().GetLineSpan().EndLinePosition.Line;
            int startLine = usings[i + 1].GetLocation().GetLineSpan().StartLinePosition.Line;

            // Check for blank lines between end of one using and start of next
            for (int line = endLine + 1; line < startLine; line++)
            {
                if (line < text.Lines.Count && text.Lines[line].ToString().Trim().Length == 0)
                {
                    hasGroupSeparator = true;
                    break;
                }
            }

            if (hasGroupSeparator) break;
        }

        if (hasGroupSeparator)
            _groupedCount++;
        else
            _ungroupedCount++;
    }

    private static bool IsSortedAlpha(List<string> names)
    {
        for (int i = 1; i < names.Count; i++)
        {
            if (string.Compare(names[i - 1], names[i], StringComparison.OrdinalIgnoreCase) > 0)
                return false;
        }

        return true;
    }

    public DetectorResult GetResult()
    {
        // D1: Alphabetically sorted
        var sortTotal = _sortedCount + _unsortedCount;
        bool alphabeticallySorted = _sortedCount >= _unsortedCount;
        double sortConfidence = sortTotal > 0
            ? (double)Math.Max(_sortedCount, _unsortedCount) / sortTotal * 100
            : 100;

        // D2: System-first
        var systemTotal = _systemFirstCount + _systemMixedCount;
        bool systemFirst = _systemFirstCount > _systemMixedCount;
        double systemConfidence = systemTotal > 0
            ? (double)Math.Max(_systemFirstCount, _systemMixedCount) / systemTotal * 100
            : 100;

        // D3: Separate groups
        var groupTotal = _groupedCount + _ungroupedCount;
        bool separateGroups = _groupedCount > _ungroupedCount;
        double groupConfidence = groupTotal > 0
            ? (double)Math.Max(_groupedCount, _ungroupedCount) / groupTotal * 100
            : 100;

        // D4: Placement
        var placementTotal = _outsideCount + _insideCount;
        string placement = _outsideCount >= _insideCount ? "outside_namespace" : "inside_namespace";
        double placementConfidence = placementTotal > 0
            ? (double)Math.Max(_outsideCount, _insideCount) / placementTotal * 100
            : 100;

        // Overall confidence = minimum of all sub-rule confidences
        double confidence = new[] { sortConfidence, systemConfidence, groupConfidence, placementConfidence }.Min();

        var sampleCount = sortTotal + systemTotal + groupTotal + placementTotal;

        var patternParts = new List<string>();
        patternParts.Add(alphabeticallySorted ? "alphabetically sorted" : "not sorted");
        patternParts.Add(systemFirst ? "System.* first" : "System.* mixed");
        patternParts.Add(separateGroups ? "grouped with blank lines" : "no group separation");
        patternParts.Add(placement);

        return new DetectorResult
        {
            DetectorName = Name,
            SampleCount = sampleCount,
            Confidence = Math.Round(confidence, 1),
            DominantPattern = string.Join(", ", patternParts),
            Details = new Dictionary<string, object>
            {
                ["AlphabeticallySorted"] = alphabeticallySorted,
                ["SystemFirst"] = systemFirst,
                ["SeparateGroups"] = separateGroups,
                ["Placement"] = placement,
                ["SortedCount"] = _sortedCount,
                ["UnsortedCount"] = _unsortedCount,
                ["SystemFirstCount"] = _systemFirstCount,
                ["SystemMixedCount"] = _systemMixedCount,
                ["GroupedCount"] = _groupedCount,
                ["UngroupedCount"] = _ungroupedCount,
                ["OutsideCount"] = _outsideCount,
                ["InsideCount"] = _insideCount,
                ["SortConfidence"] = $"{sortConfidence:F1}%",
                ["SystemConfidence"] = $"{systemConfidence:F1}%",
                ["GroupConfidence"] = $"{groupConfidence:F1}%",
                ["PlacementConfidence"] = $"{placementConfidence:F1}%",
            },
            Examples = _examples.Build("sorted", new Dictionary<string, string>
            {
                ["sorted"] = "alphabetically sorted usings",
                ["unsorted"] = "usings not in alphabetical order",
            }),
        };
    }
}
