using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StyleLearner.Fixers;

public class UsingDirectiveFixer : ILayoutFixer
{
    private readonly UsingDirectiveRule _rule;

    public string Name => "Using Directives";

    public UsingDirectiveFixer(UsingDirectiveRule rule)
    {
        _rule = rule;
    }

    public FixerResult Fix(SyntaxTree tree)
    {
        var source = tree.GetRoot().ToFullString();

        // Skip auto-generated files
        if (source.Contains("// <auto-generated"))
            return new FixerResult { Tree = tree, ChangesApplied = 0 };

        var root = (CompilationUnitSyntax)tree.GetRoot();
        var text = tree.GetText();
        int changes = 0;
        var newSource = source;

        // Fix top-level usings (outside namespace)
        var topLevelUsings = root.Usings
            .Where(u => !u.GlobalKeyword.IsKind(SyntaxKind.GlobalKeyword))
            .ToList();

        if (topLevelUsings.Count >= 2)
        {
            var result = FixUsingBlock(topLevelUsings, newSource);
            if (result.Changed)
            {
                newSource = result.NewSource;
                changes += result.ChangeCount;
            }
        }

        // Fix block-scoped namespace usings (inside namespace)
        if (changes > 0)
        {
            // Re-parse after top-level changes
            tree = CSharpSyntaxTree.ParseText(newSource, path: tree.FilePath);
            root = (CompilationUnitSyntax)tree.GetRoot();
        }

        foreach (var ns in root.Members.OfType<NamespaceDeclarationSyntax>())
        {
            var nsUsings = ns.Usings
                .Where(u => !u.GlobalKeyword.IsKind(SyntaxKind.GlobalKeyword))
                .ToList();

            if (nsUsings.Count >= 2)
            {
                var result = FixUsingBlock(nsUsings, newSource);
                if (result.Changed)
                {
                    newSource = result.NewSource;
                    changes += result.ChangeCount;
                }
            }
        }

        if (changes == 0)
            return new FixerResult { Tree = tree, ChangesApplied = 0 };

        var newTree = CSharpSyntaxTree.ParseText(newSource, path: tree.FilePath);
        return new FixerResult
        {
            Tree = newTree,
            ChangesApplied = changes,
        };
    }

    private UsingBlockFixResult FixUsingBlock(List<UsingDirectiveSyntax> usings, string source)
    {
        // Classify usings
        var regularUsings = new List<UsingDirectiveSyntax>();
        var staticUsings = new List<UsingDirectiveSyntax>();
        var aliasUsings = new List<UsingDirectiveSyntax>();

        foreach (var u in usings)
        {
            if (u.Alias != null)
                aliasUsings.Add(u);
            else if (u.StaticKeyword.IsKind(SyntaxKind.StaticKeyword))
                staticUsings.Add(u);
            else
                regularUsings.Add(u);
        }

        // Sort regular usings
        List<string> sortedRegularNames;
        if (_rule.SystemFirst)
        {
            var systemNames = regularUsings
                .Select(u => u.Name?.ToString() ?? "")
                .Where(n => n.StartsWith("System"))
                .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
                .ToList();
            var otherNames = regularUsings
                .Select(u => u.Name?.ToString() ?? "")
                .Where(n => !n.StartsWith("System"))
                .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
                .ToList();
            sortedRegularNames = systemNames.Concat(otherNames).ToList();
        }
        else
        {
            sortedRegularNames = regularUsings
                .Select(u => u.Name?.ToString() ?? "")
                .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        // Sort static usings
        var sortedStaticNames = staticUsings
            .Select(u => u.Name?.ToString() ?? "")
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();

        // Sort alias usings
        var sortedAliasLines = aliasUsings
            .Select(u => u.ToString().TrimEnd())
            .OrderBy(a => a, StringComparer.OrdinalIgnoreCase)
            .ToList();

        // Build the new using block lines
        var newLines = new List<string>();
        string? previousPrefix = null;

        foreach (var name in sortedRegularNames)
        {
            if (_rule.SeparateGroups && previousPrefix != null)
            {
                var currentPrefix = GetGroupPrefix(name);
                if (currentPrefix != previousPrefix)
                    newLines.Add("");
            }

            newLines.Add($"using {name};");
            previousPrefix = GetGroupPrefix(name);
        }

        if (sortedStaticNames.Count > 0)
        {
            if (newLines.Count > 0)
                newLines.Add("");
            foreach (var name in sortedStaticNames)
                newLines.Add($"using static {name};");
        }

        if (sortedAliasLines.Count > 0)
        {
            if (newLines.Count > 0)
                newLines.Add("");
            newLines.AddRange(sortedAliasLines);
        }

        // Get the original using block text span
        var firstUsing = usings.First();
        var lastUsing = usings.Last();

        int startOffset = firstUsing.SpanStart;
        int endOffset = lastUsing.Span.End;

        // Check for leading trivia on first using (preserve any comments before the using block)
        // but we want to start replacing from the "using" keyword itself
        var originalBlock = source.Substring(startOffset, endOffset - startOffset);

        // Detect the indentation from the first using
        var firstUsingLine = firstUsing.GetLocation().GetLineSpan().StartLinePosition;
        var sourceText = CSharpSyntaxTree.ParseText(source).GetText();
        var line = sourceText.Lines[firstUsingLine.Line];
        var lineStr = line.ToString();
        var indent = lineStr.Substring(0, lineStr.Length - lineStr.TrimStart().Length);

        // Build the new block with proper indentation
        var newBlock = string.Join(Environment.NewLine,
            newLines.Select(l => l.Length > 0 ? indent + l : ""));

        if (originalBlock == newBlock)
            return new UsingBlockFixResult { Changed = false };

        // Replace in source
        var newSource = source.Substring(0, startOffset) + newBlock + source.Substring(endOffset);

        return new UsingBlockFixResult
        {
            Changed = true,
            NewSource = newSource,
            ChangeCount = 1,
        };
    }

    private static string GetGroupPrefix(string namespaceName)
    {
        if (namespaceName.StartsWith("System"))
            return "System";
        if (namespaceName.StartsWith("Microsoft"))
            return "Microsoft";

        // Project namespace — use first segment
        int dot = namespaceName.IndexOf('.');
        return dot > 0 ? namespaceName.Substring(0, dot) : namespaceName;
    }

    private class UsingBlockFixResult
    {
        public bool Changed { get; init; }
        public string NewSource { get; init; } = "";
        public int ChangeCount { get; init; }
    }
}
