using StyleLearner.Detectors;

namespace StyleLearner.Output;

public class EditorConfigGenerator
{
    public string Generate(StyleReport report)
    {
        var lines = new List<string>
        {
            "# Generated by StyleLearner",
            $"# Analyzed: {report.AnalyzedPath}",
            $"# Files: {report.TotalFiles}, Lines: {report.TotalLines}",
            $"# Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}",
            "",
            "root = true",
            "",
            "[*.cs]",
            "",
            "# Universal whitespace rules (always applied)",
            "insert_final_newline = true",
            "end_of_line = lf",
            "trim_trailing_whitespace = true",
            "charset = utf-8",
        };

        foreach (var result in report.Results)
        {
            lines.AddRange(GenerateRules(result));
        }

        return string.Join(Environment.NewLine, lines);
    }

    private static IEnumerable<string> GenerateRules(DetectorResult result)
    {
        var rules = new List<string>();

        switch (result.DetectorName)
        {
            case "Indentation":
                GenerateIndentationRules(result, rules);
                break;
            case "Brace Style":
                GenerateBraceRules(result, rules);
                break;
            case "Line Length":
                GenerateLineLengthRules(result, rules);
                break;
            case "Using Layout":
                GenerateUsingRules(result, rules);
                break;
            case "Expression Body":
                GenerateExpressionBodyRules(result, rules);
                break;
            case "Parameter Layout":
                GenerateParameterLayoutRules(result, rules);
                break;
            case "Object Initializer":
                GenerateObjectInitializerRules(result, rules);
                break;
            case "Spacing":
                GenerateSpacingRules(result, rules);
                break;
            case "Newline Before Keywords":
                GenerateNewLineKeywordRules(result, rules);
                break;
            case "Continuation Indent":
                GenerateContinuationIndentRules(result, rules);
                break;
        }

        if (rules.Count > 0)
        {
            rules.Insert(0, "");
            rules.Insert(1, $"# {result.DetectorName} (confidence: {result.Confidence:F1}%, samples: {result.SampleCount})");
        }

        return rules;
    }

    private static void GenerateIndentationRules(DetectorResult result, List<string> rules)
    {
        var style = result.Details.GetValueOrDefault("Style", "space").ToString();
        var size = result.Details.GetValueOrDefault("Size", 4);

        rules.Add($"indent_style = {style}");
        rules.Add($"indent_size = {size}");
        rules.Add($"tab_width = {size}");
    }

    private static void GenerateBraceRules(DetectorResult result, List<string> rules)
    {
        var style = result.Details.GetValueOrDefault("Style", "allman").ToString();

        // .editorconfig csharp_new_line_before_open_brace
        if (style == "allman")
        {
            rules.Add("csharp_new_line_before_open_brace = all");
        }
        else
        {
            rules.Add("csharp_new_line_before_open_brace = none");
        }
    }

    private static void GenerateLineLengthRules(DetectorResult result, List<string> rules)
    {
        if (result.Details.TryGetValue("P90", out var p90))
        {
            // Use P90 as the basis — reflects where code naturally wraps,
            // P95/P99 are skewed by intentionally long lines (LINQ, strings, etc.)
            var maxLength = (int)Math.Ceiling(Convert.ToDouble(p90) / 10.0) * 10;
            rules.Add($"max_line_length = {maxLength}");
        }
    }

    private static void GenerateUsingRules(DetectorResult result, List<string> rules)
    {
        var placement = result.Details.GetValueOrDefault("Placement", "outside").ToString();
        var systemFirst = result.Details.GetValueOrDefault("SystemFirst", true);
        var sorted = result.Details.GetValueOrDefault("Sorted", true);

        if (placement == "outside")
        {
            rules.Add("csharp_using_directive_placement = outside_namespace:suggestion");
        }
        else
        {
            rules.Add("csharp_using_directive_placement = inside_namespace:suggestion");
        }

        rules.Add($"dotnet_sort_system_directives_first = {systemFirst.ToString()!.ToLower()}");
        rules.Add($"dotnet_separate_import_directive_groups = {(Convert.ToBoolean(systemFirst) ? "true" : "false")}");
    }

    private static void GenerateExpressionBodyRules(DetectorResult result, List<string> rules)
    {
        var methodExpr = Convert.ToInt32(result.Details.GetValueOrDefault("MethodExpressionBodyCount", 0));
        var methodBlock = Convert.ToInt32(result.Details.GetValueOrDefault("MethodBlockBodyCount", 0));
        var propExpr = Convert.ToInt32(result.Details.GetValueOrDefault("PropertyExpressionBodyCount", 0));
        var propBlock = Convert.ToInt32(result.Details.GetValueOrDefault("PropertyBlockBodyCount", 0));

        string methodPref = methodExpr > methodBlock ? "when_on_single_line" : "false";
        string propPref = propExpr > propBlock ? "when_on_single_line" : "false";

        rules.Add($"csharp_style_expression_bodied_methods = {methodPref}:suggestion");
        rules.Add($"csharp_style_expression_bodied_properties = {propPref}:suggestion");
    }

    private static void GenerateParameterLayoutRules(DetectorResult result, List<string> rules)
    {
        var closingParen = result.Details.GetValueOrDefault("ClosingParen", "own_line").ToString();
        var wrap = closingParen == "own_line"
            ? "csharp_wrap_parameters_style = chop_always"
            : "csharp_wrap_parameters_style = chop_if_long";

        rules.Add($"# Closing paren: {closingParen}");
        rules.Add($"# {wrap} (ReSharper/Rider style)");
    }

    private static void GenerateObjectInitializerRules(DetectorResult result, List<string> rules)
    {
        var trailingComma = Convert.ToBoolean(result.Details.GetValueOrDefault("TrailingComma", false));
        rules.Add($"# Trailing comma in initializers: {(trailingComma ? "yes" : "no")}");
    }

    private static void GenerateSpacingRules(DetectorResult result, List<string> rules)
    {
        var spaceAfterCast = Convert.ToBoolean(result.Details.GetValueOrDefault("SpaceAfterCast", false));
        var spaceAfterKeyword = Convert.ToBoolean(result.Details.GetValueOrDefault("SpaceAfterKeyword", true));

        rules.Add($"csharp_space_after_cast = {spaceAfterCast.ToString().ToLower()}");
        rules.Add($"csharp_space_after_keywords_in_control_flow_statements = {spaceAfterKeyword.ToString().ToLower()}");
    }

    private static void GenerateContinuationIndentRules(DetectorResult result, List<string> rules)
    {
        var style = result.Details.GetValueOrDefault("OverallStyle", "relative").ToString();
        rules.Add($"# Continuation indent style: {style} (no standard .editorconfig key)");
        rules.Add($"# Chain dots and call arguments use {(style == "relative" ? "4-space relative" : "column-aligned")} indentation");
    }

    private static void GenerateNewLineKeywordRules(DetectorResult result, List<string> rules)
    {
        var newLineBeforeCatch = Convert.ToBoolean(result.Details.GetValueOrDefault("NewLineBeforeCatch", true));
        var newLineBeforeElse = Convert.ToBoolean(result.Details.GetValueOrDefault("NewLineBeforeElse", true));
        var newLineBeforeFinally = Convert.ToBoolean(result.Details.GetValueOrDefault("NewLineBeforeFinally", true));

        rules.Add($"csharp_new_line_before_catch = {newLineBeforeCatch.ToString().ToLower()}");
        rules.Add($"csharp_new_line_before_else = {newLineBeforeElse.ToString().ToLower()}");
        rules.Add($"csharp_new_line_before_finally = {newLineBeforeFinally.ToString().ToLower()}");
    }
}
