using System.Text;
using System.Web;
using StyleLearner.Detectors;

namespace StyleLearner.Output;

public class HtmlReporter
{
    public string Generate(StyleReport report)
    {
        var sb = new StringBuilder();

        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine($"<title>StyleLearner Report — {Esc(Path.GetFileName(report.AnalyzedPath))}</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(Css());
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");

        // Header
        sb.AppendLine("<header>");
        sb.AppendLine("<h1>StyleLearner Analysis Report</h1>");
        sb.AppendLine("<div class=\"meta\">");
        sb.AppendLine($"<span><strong>Path:</strong> {Esc(report.AnalyzedPath)}</span>");
        sb.AppendLine($"<span><strong>Files:</strong> {report.TotalFiles:N0}</span>");
        sb.AppendLine($"<span><strong>Lines:</strong> {report.TotalLines:N0}</span>");
        sb.AppendLine($"<span><strong>Generated:</strong> {DateTime.Now:yyyy-MM-dd HH:mm:ss}</span>");
        sb.AppendLine("</div>");
        sb.AppendLine("</header>");

        // Consistency score gauge
        var score = report.ConsistencyScore;
        var scoreClass = score >= 90 ? "high" : score >= 70 ? "mid" : "low";
        var dashOffset = 251.2 - (251.2 * score / 100); // SVG circle circumference = 2*PI*40 ≈ 251.2
        sb.AppendLine("<section class=\"score-section\">");
        sb.AppendLine("<div class=\"score-gauge\">");
        sb.AppendLine("<svg viewBox=\"0 0 100 100\" width=\"120\" height=\"120\">");
        sb.AppendLine("<circle cx=\"50\" cy=\"50\" r=\"40\" class=\"score-bg\"/>");
        sb.AppendLine($"<circle cx=\"50\" cy=\"50\" r=\"40\" class=\"score-ring {scoreClass}\" stroke-dasharray=\"251.2\" stroke-dashoffset=\"{dashOffset:F1}\" transform=\"rotate(-90 50 50)\"/>");
        sb.AppendLine("</svg>");
        sb.AppendLine($"<div class=\"score-value {scoreClass}\">{score:F1}%</div>");
        sb.AppendLine("</div>");
        sb.AppendLine("<div class=\"score-label\">");
        sb.AppendLine("<h2>Consistency Score</h2>");
        sb.AppendLine("<p>Weighted average of all detector confidences</p>");
        sb.AppendLine("</div>");
        sb.AppendLine("</section>");

        // Summary cards
        sb.AppendLine("<section class=\"summary\">");
        foreach (var result in report.Results)
        {
            var confClass = result.Confidence >= 90 ? "high" : result.Confidence >= 70 ? "mid" : "low";
            sb.AppendLine($"<a href=\"#{Slug(result.DetectorName)}\" class=\"card\">");
            sb.AppendLine($"  <div class=\"card-name\">{Esc(result.DetectorName)}</div>");
            sb.AppendLine($"  <div class=\"card-conf {confClass}\">{result.Confidence:F1}%</div>");
            sb.AppendLine($"  <div class=\"card-pattern\">{Esc(Truncate(result.DominantPattern, 60))}</div>");
            sb.AppendLine("</a>");
        }
        sb.AppendLine("</section>");

        // Detector sections
        foreach (var result in report.Results)
        {
            WriteDetector(sb, result, report.AnalyzedPath);
        }

        sb.AppendLine("<footer>Generated by StyleLearner</footer>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }

    private void WriteDetector(StringBuilder sb, DetectorResult result, string basePath)
    {
        var confClass = result.Confidence >= 90 ? "high" : result.Confidence >= 70 ? "mid" : "low";

        sb.AppendLine($"<section class=\"detector\" id=\"{Slug(result.DetectorName)}\">");
        sb.AppendLine($"<h2>{Esc(result.DetectorName)}</h2>");

        // Pattern + stats bar
        sb.AppendLine("<div class=\"stats\">");
        sb.AppendLine($"<div class=\"stat\"><label>Pattern</label><span class=\"pattern\">{Esc(result.DominantPattern)}</span></div>");
        sb.AppendLine($"<div class=\"stat\"><label>Confidence</label><span class=\"conf {confClass}\">{result.Confidence:F1}%</span></div>");
        sb.AppendLine($"<div class=\"stat\"><label>Samples</label><span>{result.SampleCount:N0}</span></div>");
        sb.AppendLine("</div>");

        // Details table
        if (result.Details.Count > 0)
        {
            sb.AppendLine("<details><summary>Details</summary>");
            sb.AppendLine("<table class=\"details\">");
            foreach (var (key, value) in result.Details)
            {
                sb.AppendLine($"<tr><td class=\"key\">{Esc(key)}</td><td>{Esc(value.ToString() ?? "")}</td></tr>");
            }
            sb.AppendLine("</table>");
            sb.AppendLine("</details>");
        }

        // Examples
        if (result.Examples.Count > 0)
        {
            var conforming = result.Examples.Where(e => e.IsConforming).ToList();
            var nonConforming = result.Examples.Where(e => !e.IsConforming).ToList();
            var singleGroup = conforming.Count == 0 || nonConforming.Count == 0;

            sb.AppendLine($"<div class=\"examples{(singleGroup ? " single-group" : "")}\">");

            if (conforming.Count > 0)
            {
                sb.AppendLine("<div class=\"example-group conforming\">");
                sb.AppendLine("<h3>&#10003; Conforming</h3>");
                foreach (var ex in conforming)
                    WriteExample(sb, ex, basePath, true);
                sb.AppendLine("</div>");
            }

            if (nonConforming.Count > 0)
            {
                sb.AppendLine("<div class=\"example-group non-conforming\">");
                sb.AppendLine("<h3>&#10007; Non-conforming</h3>");
                foreach (var ex in nonConforming)
                    WriteExample(sb, ex, basePath, false);
                sb.AppendLine("</div>");
            }

            sb.AppendLine("</div>");
        }

        sb.AppendLine("</section>");
    }

    private void WriteExample(StringBuilder sb, StyleExample ex, string basePath, bool conforming)
    {
        var relPath = ShortenPath(ex.FilePath, basePath);
        var cls = conforming ? "conforming" : "non-conforming";

        sb.AppendLine($"<div class=\"example {cls}\">");
        sb.AppendLine($"<div class=\"example-header\">");
        sb.AppendLine($"<span class=\"file\">{Esc(relPath)}:{ex.LineNumber}</span>");
        sb.AppendLine($"<span class=\"label\">{Esc(ex.Label)}</span>");
        sb.AppendLine("</div>");
        sb.AppendLine($"<pre><code>{Esc(ex.Snippet)}</code></pre>");
        sb.AppendLine("</div>");
    }

    private static string ShortenPath(string path, string basePath)
    {
        if (!string.IsNullOrEmpty(basePath))
            return Path.GetRelativePath(basePath, path).Replace('\\', '/');

        var parts = path.Replace('\\', '/').Split('/');
        return parts.Length > 2 ? string.Join("/", parts[^2..]) : parts[^1];
    }

    private static string Esc(string text) => HttpUtility.HtmlEncode(text);

    private static string Slug(string text) => text.ToLowerInvariant().Replace(' ', '-').Replace("&", "");

    private static string Truncate(string text, int max)
        => text.Length <= max ? text : text[..(max - 1)] + "…";

    private static string Css() => """
        :root {
            --bg: #1a1b26;
            --surface: #24283b;
            --surface2: #2f3348;
            --border: #3b3f54;
            --text: #c0caf5;
            --text-muted: #787c99;
            --accent: #7aa2f7;
            --green: #9ece6a;
            --red: #f7768e;
            --yellow: #e0af68;
            --orange: #ff9e64;
            --cyan: #7dcfff;
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem 3rem;
            max-width: 1450px;
            margin: 0 auto;
        }

        header {
            margin-bottom: 2rem;
            padding-bottom: 1.5rem;
            border-bottom: 2px solid var(--border);
        }

        h1 {
            color: var(--cyan);
            font-size: 1.8rem;
            margin-bottom: 0.75rem;
        }

        .meta {
            display: flex;
            gap: 2rem;
            flex-wrap: wrap;
            color: var(--text-muted);
            font-size: 0.9rem;
        }

        .summary {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 0.75rem;
            margin-bottom: 2.5rem;
        }

        .card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1rem;
            text-decoration: none;
            color: inherit;
            transition: border-color 0.2s, transform 0.2s;
        }

        .card:hover {
            border-color: var(--accent);
            transform: translateY(-2px);
        }

        .card-name {
            font-weight: 600;
            font-size: 0.85rem;
            color: var(--text);
            margin-bottom: 0.25rem;
        }

        .card-conf {
            font-size: 1.4rem;
            font-weight: 700;
            margin-bottom: 0.25rem;
        }

        .card-pattern {
            font-size: 0.75rem;
            color: var(--text-muted);
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .detector {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
            overflow: hidden;
        }

        .detector h2 {
            color: var(--accent);
            font-size: 1.3rem;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 1px solid var(--border);
        }

        .stats {
            display: flex;
            gap: 2rem;
            flex-wrap: wrap;
            margin-bottom: 1rem;
        }

        .stat label {
            display: block;
            font-size: 0.7rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-muted);
            margin-bottom: 0.15rem;
        }

        .stat .pattern {
            color: var(--cyan);
            font-size: 0.9rem;
        }

        .conf {
            font-weight: 700;
            font-size: 1.1rem;
        }

        .high { color: var(--green); }
        .mid { color: var(--yellow); }
        .low { color: var(--red); }

        details {
            margin-bottom: 1rem;
        }

        details summary {
            cursor: pointer;
            color: var(--text-muted);
            font-size: 0.85rem;
            margin-bottom: 0.5rem;
        }

        details summary:hover {
            color: var(--text);
        }

        table.details {
            width: 100%;
            font-size: 0.8rem;
            border-collapse: collapse;
        }

        table.details td {
            padding: 0.2rem 0.5rem;
            border-bottom: 1px solid var(--border);
            vertical-align: top;
        }

        table.details .key {
            color: var(--text-muted);
            white-space: nowrap;
            width: 1%;
        }

        .examples {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1rem;
        }

        .examples.single-group {
            grid-template-columns: 1fr;
        }

        @media (max-width: 800px) {
            .examples { grid-template-columns: 1fr; }
        }

        .example-group {
            min-width: 0;
        }

        .example-group h3 {
            font-size: 0.85rem;
            font-weight: 600;
            margin-bottom: 0.5rem;
        }

        .example-group.conforming h3 { color: var(--green); }
        .example-group.non-conforming h3 { color: var(--red); }

        .example {
            background: var(--surface2);
            border-radius: 6px;
            margin-bottom: 0.75rem;
            overflow: hidden;
        }

        .example.conforming { border-left: 3px solid var(--green); }
        .example.non-conforming { border-left: 3px solid var(--red); }

        .example-header {
            padding: 0.4rem 0.75rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 0.5rem;
            flex-wrap: wrap;
        }

        .example-header .file {
            font-family: 'Cascadia Code', 'Fira Code', monospace;
            font-size: 0.75rem;
            color: var(--text-muted);
        }

        .example-header .label {
            font-size: 0.75rem;
            color: var(--orange);
        }

        .example pre {
            background: var(--bg);
            margin: 0;
            padding: 0.75rem;
            overflow-x: auto;
            font-size: 0.8rem;
            line-height: 1.5;
            max-width: 100%;
        }

        .example code {
            font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
            color: var(--text);
            white-space: pre;
        }

        .score-section {
            display: flex;
            align-items: center;
            gap: 1.5rem;
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 1.5rem;
            margin-bottom: 2rem;
        }

        .score-gauge {
            position: relative;
            width: 120px;
            height: 120px;
            flex-shrink: 0;
        }

        .score-bg {
            fill: none;
            stroke: var(--surface2);
            stroke-width: 8;
        }

        .score-ring {
            fill: none;
            stroke-width: 8;
            stroke-linecap: round;
            transition: stroke-dashoffset 0.6s ease;
        }

        .score-ring.high { stroke: var(--green); }
        .score-ring.mid { stroke: var(--yellow); }
        .score-ring.low { stroke: var(--red); }

        .score-value {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 1.4rem;
            font-weight: 700;
        }

        .score-label h2 {
            color: var(--text);
            font-size: 1.2rem;
            margin-bottom: 0.25rem;
            border: none;
            padding: 0;
        }

        .score-label p {
            color: var(--text-muted);
            font-size: 0.85rem;
        }

        footer {
            text-align: center;
            color: var(--text-muted);
            font-size: 0.8rem;
            padding: 2rem 0 1rem;
        }
        """;
}
